type TopicDef = {
  slug: string;
  title: string;
  description: string;
  iconName: string;
  sortOrder: number;
  words: string[];
};

export const topicDefs: TopicDef[] = [
  {
    slug: 'animals',
    title: 'Животные',
    description: 'Домашние и дикие животные, птицы, насекомые',
    iconName: 'Bug02Icon',
    sortOrder: 1,
    words: [
      'aardvark', 'alligator', 'alpaca', 'animal', 'antelope', 'ape', 'armadillo', 'baboon',
      'badger', 'bat', 'bear', 'beaver', 'bison', 'boar', 'breed', 'buffalo',
      'bull', 'cage', 'camel', 'canary', 'capybara', 'cat', 'chameleon', 'cheetah',
      'chimpanzee', 'chinchilla', 'chipmunk', 'cougar', 'cow', 'coyote', 'crocodile', 'crow',
      'deer', 'dingo', 'dog', 'donkey', 'dromedary', 'elephant', 'elk', 'ewe',
      'feather', 'ferret', 'finch', 'fish', 'flock', 'fox', 'frog', 'fur',
      'gazelle', 'gila monster', 'giraffe', 'gnu', 'goat', 'gopher', 'gorilla', 'grizzly bear',
      'ground hog', 'guinea pig', 'hamster', 'hedgehog', 'herd', 'hippopotamus', 'hog', 'horse',
      'hunt', 'hyena', 'ibex', 'iguana', 'impala', 'jackal', 'jaguar', 'kangaroo',
      'kitten', 'koala', 'lamb', 'lemur', 'leopard', 'lion', 'lizard', 'llama',
      'lynx', 'mandrill', 'marmoset', 'mink', 'mole', 'mongoose', 'monkey', 'moose',
      'mountain goat', 'mouse', 'mule', 'muskrat', 'mustang', 'mynah bird', 'nest', 'newt',
      'ocelot', 'opossum', 'orangutan', 'oryx', 'otter', 'ox', 'panda', 'panther',
      'parakeet', 'parrot', 'paw', 'pet', 'pig', 'platypus', 'polar bear', 'porcupine',
      'porpoise', 'prairie dog', 'predator', 'prey', 'puma', 'puppy', 'rabbit', 'raccoon',
      'ram', 'rat', 'reindeer', 'reptile', 'rhinoceros', 'salamander', 'seal', 'sheep',
      'shrew', 'silver fox', 'skunk', 'sloth', 'snake', 'squirrel', 'tail', 'tapir',
      'tiger', 'toad', 'turtle', 'walrus', 'warthog', 'weasel', 'whale', 'wild',
      'wildcat', 'wing', 'wolf', 'wolverine', 'wombat', 'woodchuck', 'yak', 'zebra',
    ],
  },
  {
    slug: 'food-drinks',
    title: 'Еда и напитки',
    description: 'Продукты, блюда, напитки и всё, что связано с едой',
    iconName: 'CoffeeIcon',
    sortOrder: 2,
    words: [
      'acorn squash', 'aioli', 'ajvar', 'ajwain', 'alfalfa sprout', 'alligator pepper', 'allspice', 'amaranth',
      'amba', 'amchoor', 'angelica', 'anise', 'aonori', 'appetite', 'appetizer', 'apple',
      'apricot', 'aromatic ginger', 'artichoke', 'arugula', 'asafoetida', 'asparagus', 'aubergine', 'avocado',
      'azuki bean', 'banana', 'banana ketchup', 'banana squash', 'barbecue sauce', 'basil', 'bay leaf', 'bean',
      'bean sprout', 'beer', 'beet', 'bell pepper', 'biber salçası', 'bilberry', 'bitter', 'black bean',
      'black cardamom', 'black mustard', 'black peppercorn', 'black vinegar', 'black-eyed pea', 'blackberry', 'blackcurrant', 'blood orange',
      'blueberry', 'bok choy', 'boldo', 'bolivian coriander', 'borage', 'borlotti bean', 'boysenberry', 'brazilian pepper',
      'bread', 'breadfruit', 'breakfast', 'broad beans', 'broccoflower', 'broccoli', 'brown mustard', 'brussels sprout',
      'bunium persicum', 'butter', 'butternut squash', 'cabbage', 'cake', 'calabrese', 'camphor', 'canary melon',
      'candy', 'cantaloupe', 'caraway', 'cardamom', 'carrot', 'cassia', 'cauliflower', 'cayenne pepper',
      'celeriac', 'celery', 'celery powder', 'celery seed', 'cereal', 'chamomile', 'chard', 'charoli',
      'chayote', 'cheese', 'chenpi', 'cherimoya', 'cherry', 'chervil', 'chicken', 'chickpea',
      'chili oil', 'chili pepper', 'chili peppers', 'chili sauce', 'chimichurri', 'chives', 'chocolate', 'chrain',
      'chutney', 'cicely', 'cilantro', 'cinnamon', 'clementine', 'cloudberry', 'clove', 'cocktail sauce',
      'coconut', 'coffee', 'collard green', 'colo-colo', 'cookie', 'coriander leaf', 'coriander seed', 'corn',
      'corn salad', 'courgette', 'cranberry', 'cream', 'cress', 'cubeb', 'cucumber', 'culantro',
      'cumin', 'currant', 'curry ketchup', 'curry leaf', 'dabu-dabu', 'daikon', 'damson', 'date',
      'delicata', 'delicious', 'dessert', 'diet', 'dijon ketchup', 'dijon mustard', 'dill', 'dill seed',
      'dinner', 'dip', 'dish', 'dough', 'dragonfruit', 'dried lime', 'drink', 'durian',
      'eat', 'egg', 'eggplant', 'elderberry', 'endive', 'epazote', 'feijoa', 'fennel',
      'fenugreek', 'fiddlehead', 'fig', 'fingerroot', 'fish', 'fish paste', 'fish sauce', 'flour',
      'food', 'fresh', 'frisee', 'fritessaus', 'fruit ketchup', 'fruit preserves', 'fry sauce', 'garlic',
      'garlic chives', 'gem squash', 'ginger', 'gochujang', 'goji berry', 'golpar', 'gooseberry', 'grain',
      'grape', 'grapefruit', 'greater galangal', 'green bean', 'green pepper', 'green peppercorn', 'guacamole', 'guava',
      'habanero', 'hemp', 'hoja santa', 'holy basil', 'honey dill', 'honeydew', 'horseradish', 'hot mustard',
      'hot sauce', 'houttuynia cordata', 'hubbard squash', 'huckleberry', 'hungry', 'hyssop', 'ingredient', 'jackfruit',
      'jalapeno', 'jambul', 'jerusalem artichoke', 'jicama', 'jimbu', 'juice', 'jujube', 'juniper berry',
      'kachumbari', 'kachumber', 'kale', 'ketchup', 'khrenovina', 'kidney bean', 'kimchi', 'kinh gioi',
      'kiwi fruit', 'kohlrabi', 'kokum', 'korarima', 'kumquat', 'kyopolou', 'lavender', 'leek',
      'legume', 'lemon', 'lemon balm', 'lemon grass', 'lemon myrtle', 'lemon verbena', 'lentils', 'lesser galangal',
      'lettuce', 'lima bean', 'lime', 'limnophila aromatica', 'liquorice', 'litsea cubeba', 'ljutenica', 'long pepper',
      'loquat', 'lovage', 'lunch', 'lychee', 'mace', 'mahlab', 'mamey', 'mandarine',
      'mangetout', 'mango', 'mango pickle', 'mango-ginger', 'marjoram', 'mastic', 'mayonnaise', 'meal',
      'meat', 'mignonette sauce', 'milk', 'milkette', 'mint', 'mitsuba', 'mostarda', 'mugwort',
      'muhammara', 'mulberry', 'mumbo sauce', 'mung bean', 'murri', 'mushroom', 'mushroom ketchup', 'mustard',
      'mustard green', 'mustard oil', 'navy bean', 'nectarine', 'nigella', 'nigella sativa', 'njangsa', 'noodle',
      'nopale', 'nut', 'nutmeg', 'nutrition', 'nutritional yeast', 'oil', 'okra', 'olive',
      'olive oil', 'onion', 'orange', 'oregano', 'papaya', 'paprika', 'parsley', 'parsnip',
      'passionfruit', 'pasta', 'patty pan', 'pea', 'peach', 'pear', 'pepper jelly', 'perilla',
      'persimmon', 'peruvian pepper', 'pesto', 'physalis', 'piccalilli', 'pickled cucumber', 'pickled fruit', 'pickled onion',
      'pickled pepper', 'pie', 'pineapple', 'pinto bean', 'pinđur', 'pizza', 'plum', 'pomegranate',
      'pomegranate seed', 'pomelo', 'popcorn seasoning', 'poppy seed', 'portion', 'potato', 'pumpkin', 'purple mangosteen',
      'quince', 'radhuni', 'radicchio', 'radish', 'raisin', 'rambutan', 'raspberry', 'raw',
      'recipe', 'redcurrant', 'relish', 'remoulade', 'rhubarb', 'rice', 'ripe', 'rock melon',
      'rose', 'rosemary', 'rue', 'runner bean', 'rutabaga', 'saffron', 'sage', 'salad',
      'salad cream', 'salad dressing', 'salal berry', 'salmoriglio', 'salsa', 'salsa golf', 'salt', 'salty',
      'sambal', 'sandwich', 'sansho', 'sarsaparilla', 'sassafras', 'satsuma', 'sauce', 'sauerkraut',
      'savory', 'scallion', 'sesame', 'sesame oil', 'shallot', 'shiso', 'sichuan pepper', 'skhug',
      'skirret', 'skyronnes', 'snack', 'snap pea', 'sorrel', 'soup', 'sour', 'soy bean',
      'soy sauce', 'spaghetti squash', 'spicy', 'spinach', 'squash', 'sriracha', 'star anise', 'star fruit',
      'steak sauce', 'strawberry', 'sugar', 'sumac', 'sumbala', 'sweet', 'sweet potato', 'syrup',
      'tabasco pepper', 'tamarillo', 'tamarind', 'tangerine', 'taro', 'tarragon', 'tartar sauce', 'tasmanian pepper',
      'taste', 'tat soi', 'tea', 'tekka', 'teriyaki sauce', 'tewkesbury mustard', 'thai basil', 'thirsty',
      'thyme', 'tkemali', 'tomato', 'tonka bean', 'topinambur', 'toum', 'tubers', 'turmeric',
      'turnip', 'turun sinappi', 'ugli fruit', 'uzazi', 'vanilla', 'vietnamese coriander', 'vincotto', 'vinegar',
      'vino cotto', 'voatsiperifery', 'wasabi', 'water', 'water chestnut', 'watercress', 'watermelon', 'white mustard',
      'white peppercorn', 'white radish', 'wine', 'woodruff', 'xo sauce', 'yam', 'yuzu', 'za\'atar',
      'zacuscă', 'zedoary', 'zereshk', 'zest', 'zucchini',
    ],
  },
  {
    slug: 'home',
    title: 'Дом и жильё',
    description: 'Комнаты, мебель, бытовые предметы',
    iconName: 'Home01Icon',
    sortOrder: 3,
    words: [
      'aerary', 'aircraft cabin', 'airport lounge', 'alcove', 'anatomical theatre', 'anechoic chamber', 'antechamber', 'anteroom',
      'apartment', 'armory', 'assembly room', 'atelier', 'attic', 'auditorium', 'backroom', 'balcony',
      'ballroom', 'basement', 'bathroom', 'bed', 'bedroom', 'billiard room', 'blanket', 'boardroom',
      'boiler room', 'boudoir', 'breakfast nook', 'breezeway', 'broom', 'bucket', 'building', 'cabin',
      'cafeteria', 'caldarium', 'carpet', 'ceiling', 'cellar', 'chair', 'changing room', 'chapel',
      'chimney', 'classroom', 'clean', 'clean room', 'cloakroom', 'closet', 'cold room', 'comfortable',
      'common room', 'computer lab', 'conference room', 'conservatory', 'control room', 'conversation pit', 'corner office', 'courtroom',
      'cozy', 'cry room', 'cupboard', 'curtain', 'darkroom', 'decorate', 'den', 'desk',
      'dining room', 'door', 'dormitory', 'drawer', 'drawing room', 'dressing room', 'electrical room', 'emergency room',
      'engine room', 'equipment room', 'fallout shelter', 'family room', 'fence', 'fireplace', 'fitting room', 'flat',
      'floor', 'foyer', 'furniture', 'game room', 'garage', 'garden', 'gate', 'guest room',
      'gym', 'hallway', 'home', 'hotel room', 'house', 'iron', 'key', 'kitchen',
      'lamp', 'laundry', 'laundry room', 'library', 'living room', 'lobby', 'lock', 'locker room',
      'loft', 'lounge', 'mailroom', 'map room', 'messy', 'mirror', 'motel room', 'move',
      'mud room', 'neighbor', 'newsroom', 'nursery', 'office', 'panic room', 'pantry', 'parlor',
      'pillow', 'pipe', 'playroom', 'plug', 'pool room', 'porch', 'print room', 'rec room',
      'rent', 'roof', 'room', 'salon', 'sauna', 'schoolroom', 'shelf', 'shower',
      'showroom', 'sink', 'sitting room', 'sofa', 'staff room', 'stairs', 'stockroom', 'storm cellar',
      'studio', 'study', 'sunroom', 'table', 'tap', 'tearoom', 'throne room', 'tidy',
      'toilet', 'towel', 'trash', 'tv room', 'utility room', 'vacuum', 'waiting room', 'wall',
      'washroom', 'water closet', 'weight room', 'window', 'wine cellar', 'wiring closet', 'workshop',
    ],
  },
  {
    slug: 'clothing',
    title: 'Одежда и аксессуары',
    description: 'Одежда, обувь, аксессуары и стиль',
    iconName: 'Shirt01Icon',
    sortOrder: 4,
    words: [
      'button', 'clothes', 'collar', 'comfortable', 'cotton', 'fabric', 'fashion', 'fit',
      'fold', 'hang', 'iron', 'laundry', 'leather', 'loose', 'needle', 'pattern',
      'plain', 'pocket', 'sew', 'silk', 'size', 'sleeve', 'stain', 'stripe',
      'style', 'thread', 'tight', 'try', 'uniform', 'wear', 'wool', 'zipper',
    ],
  },
  {
    slug: 'body-health',
    title: 'Тело и здоровье',
    description: 'Части тела, здоровье, болезни, медицина',
    iconName: 'HeartCheckIcon',
    sortOrder: 5,
    words: [
      'ache', 'alive', 'allergic', 'ambulance', 'ankle', 'arm', 'back', 'bacteria',
      'belly', 'blind', 'blood', 'body', 'bone', 'bottom', 'breast', 'breath',
      'buttocks', 'calf', 'cheek', 'chin', 'cold', 'cough', 'cure', 'dead',
      'deaf', 'diagnose', 'diet', 'disease', 'dizzy', 'doctor', 'ear', 'elbow',
      'emergency', 'examine', 'exercise', 'eye', 'eyebrow', 'eyelash', 'fever', 'finger',
      'fist', 'foot', 'forearm', 'forehead', 'hair', 'hand', 'head', 'headache',
      'heal', 'health', 'hip', 'hospital', 'hurt', 'ill', 'infection', 'injury',
      'knee', 'leg', 'lip', 'lower leg', 'medicine', 'mouth', 'muscle', 'nauseous',
      'neck', 'nerve', 'nose', 'nostril', 'nurse', 'pain', 'patient', 'pharmacy',
      'pill', 'pregnant', 'prescription', 'pulse', 'recover', 'rest', 'shoulder', 'sick',
      'sleep', 'sore', 'surgery', 'swollen', 'symptom', 'temperature', 'thigh', 'thumb',
      'toe', 'tongue', 'tooth', 'treatment', 'upper arm', 'vaccine', 'virus', 'waist',
      'wound', 'wrist',
    ],
  },
  {
    slug: 'family',
    title: 'Семья и отношения',
    description: 'Родственники, отношения, семейная жизнь',
    iconName: 'UserGroupIcon',
    sortOrder: 6,
    words: [
      'adopt', 'ancestor', 'anniversary', 'argue', 'baby', 'birth', 'bond', 'care',
      'child', 'children', 'couple', 'cradle', 'descendant', 'divorce', 'engagement', 'family',
      'fiancé', 'friend', 'generation', 'heritage', 'household', 'love', 'loyalty', 'marriage',
      'neighbor', 'orphan', 'parent', 'partner', 'pregnant', 'raise', 'relationship', 'relative',
      'respect', 'support', 'trust', 'twin', 'wedding', 'widow',
    ],
  },
  {
    slug: 'work-career',
    title: 'Работа и карьера',
    description: 'Профессии, рабочий процесс, карьерный рост',
    iconName: 'Briefcase01Icon',
    sortOrder: 7,
    words: [
      'accountant', 'achieve', 'actor', 'actuary', 'adjudicator', 'administrative assistant', 'advertising manager', 'aerobics instructor',
      'aerospace engineer', 'agent', 'agricultural engineer', 'agricultural grader', 'agricultural inspector', 'agricultural manager', 'agricultural sorter', 'agricultural technician',
      'agricultural worker', 'aircraft mechanic', 'airline copilot', 'airline pilot', 'ambitious', 'ambulance dispatcher', 'ambulance driver', 'anesthesiologist',
      'animal breeder', 'animal scientist', 'animal trainer', 'animator', 'anthropologist', 'apparel patternmaker', 'apparel worker', 'apply',
      'arbitrator', 'archeologist', 'architect', 'architectural drafter', 'architectural manager', 'archivist', 'art director', 'art teacher',
      'artist', 'assembler', 'astronomer', 'athlete', 'athletic trainer', 'atmospheric scientist', 'attendant', 'audiologist',
      'auditor', 'author', 'automotive mechanic', 'avionics technician', 'back-end developer', 'baggage porter', 'bailiff', 'baker',
      'barback', 'barber', 'bartender', 'bellhop', 'bench carpenter', 'bicycle repairer', 'biochemist', 'biological technician',
      'biomedical engineer', 'biophysicist', 'blaster', 'blockmason', 'boiler operator', 'boilermaker', 'bookkeeper', 'boss',
      'brazer', 'brickmason', 'broadcast technician', 'brokerage clerk', 'budget analyst', 'building inspector', 'bus mechanic', 'business',
      'butcher', 'buyer', 'cabinetmaker', 'cafeteria attendant', 'cafeteria cook', 'camera operator', 'camera repairer', 'cardiovascular technician',
      'career', 'cargo agent', 'carpenter', 'carpet installer', 'cartographer', 'cashier', 'caster', 'cement mason',
      'chauffeur', 'checker', 'chef', 'chemical engineer', 'chemist', 'chemistry teacher', 'chief executive', 'childcare worker',
      'chiropractor', 'choreographer', 'civil drafter', 'civil engineer', 'claims adjuster', 'claims examiner', 'claims investigator', 'cleaner',
      'client', 'clinical psychologist', 'coating worker', 'coatroom attendant', 'coil finisher', 'coil taper', 'coil winder', 'colleague',
      'commercial diver', 'commercial pilot', 'communications teacher', 'company', 'compete', 'compliance officer', 'composer', 'computer operator',
      'computer programmer', 'concierge', 'conciliator', 'concrete finisher', 'conservation scientist', 'conservation worker', 'conservator', 'construction inspector',
      'construction manager', 'construction painter', 'construction worker', 'contract', 'convention planner', 'conveyor operator', 'cook', 'cooperate',
      'copy marker', 'correctional officer', 'correspondence clerk', 'correspondent', 'cosmetologist', 'cost estimator', 'costume attendant', 'counseling psychologist',
      'counselor', 'courier', 'court reporter', 'craft artist', 'crane operator', 'credit analyst', 'credit checker', 'credit counselor',
      'criminal investigator', 'crossing guard', 'curator', 'custom sewer', 'customer', 'cutter', 'dancer', 'database administrator',
      'deadline', 'deal', 'decorating worker', 'demonstrator', 'dental assistant', 'dental hygienist', 'dentist', 'department',
      'dermatologist', 'derrick operator', 'designer', 'desktop publisher', 'detective', 'develop', 'developer', 'die maker',
      'dietetic technician', 'dietitian', 'dinkey operator', 'director', 'dishwasher', 'dispatcher', 'dj', 'doctor',
      'drafter', 'dragline operator', 'drama teacher', 'dredge operator', 'dressmaker', 'drier operator', 'dry-cleaning worker', 'drywall installer',
      'earn', 'earth driller', 'economics teacher', 'economist', 'editor', 'education administrator', 'electrical engineer', 'electrical installer',
      'electrician', 'electro-mechanical technician', 'elevator installer', 'elevator repairer', 'embalmer', 'employee', 'engine assembler', 'engineer',
      'engineering manager', 'engineering teacher', 'engraver', 'entertainment attendant', 'environmental engineer', 'environmental scientist', 'epidemiologist', 'escort',
      'etcher', 'event planner', 'excavating operator', 'executive secretary', 'exhibit designer', 'expediting clerk', 'experience', 'explosives worker',
      'extraction worker', 'fabric mender', 'fabric patternmaker', 'fabricator', 'factory', 'faller', 'family practitioner', 'family therapist',
      'farm advisor', 'farmer', 'farmworker', 'fashion designer', 'fence erector', 'fiberglass fabricator', 'fiberglass laminator', 'file clerk',
      'financial analyst', 'financial examiner', 'financial manager', 'fine artist', 'fire', 'fire dispatcher', 'fire inspector', 'fire investigator',
      'firefighter', 'fish cutter', 'fish trimmer', 'fisher', 'fitness trainer', 'flight attendant', 'floor finisher', 'floor layer',
      'floor sander', 'floral designer', 'food batchmaker', 'food scientist', 'food server', 'food technologist', 'forest worker', 'forester',
      'forestry teacher', 'foundry coremaker', 'freight agent', 'freight mover', 'front-end developer', 'fundraising manager', 'funeral attendant', 'funeral director',
      'furnace operator', 'furnishings worker', 'furniture finisher', 'gaming dealer', 'gaming investigator', 'gaming manager', 'garment mender', 'garment presser',
      'gas compressor', 'general manager', 'general practitioner', 'geographer', 'geography teacher', 'geological engineer', 'geological technician', 'geoscientist',
      'glazier', 'graphic designer', 'groundskeeper', 'groundskeeping worker', 'gynecologist', 'hairdresser', 'hairstylist', 'hand laborer',
      'hand packager', 'hand packer', 'hand sewer', 'head cook', 'health educator', 'hearing officer', 'heating installer', 'heating mechanic',
      'hire', 'historian', 'history teacher', 'host', 'hostess', 'hostler', 'housekeeping cleaner', 'hunter',
      'hydrologist', 'illustrator', 'improve', 'industrial designer', 'industrial engineer', 'industry', 'information clerk', 'inspector',
      'instructional coordinator', 'instructor', 'insulation worker', 'insurance underwriter', 'interior designer', 'internist', 'interpreter', 'interview',
      'interviewer', 'investigator', 'jailer', 'janitor', 'jeweler', 'job', 'judge', 'kettle operator',
      'kiln operator', 'kindergarten teacher', 'landscape architect', 'landscaping worker', 'lathe setter', 'laundry worker', 'law teacher', 'lawyer',
      'layout worker', 'leather worker', 'legal assistant', 'legal secretary', 'legislator', 'librarian', 'library assistant', 'library technician',
      'life scientist', 'lifeguard', 'line installer', 'literacy teacher', 'literature teacher', 'loan clerk', 'loan interviewer', 'loan officer',
      'lobby attendant', 'locksmith', 'locomotive engineer', 'locomotive firer', 'lodging manager', 'log grader', 'logistician', 'machine feeder',
      'machinist', 'magistrate', 'magistrate judge', 'maid', 'mail clerk', 'mail superintendent', 'maintenance painter', 'maintenance worker',
      'makeup artist', 'manage', 'management analyst', 'manager', 'manicurist', 'mapping technician', 'marble setter', 'marine engineer',
      'marine oiler', 'marketing manager', 'marketing specialist', 'marriage therapist', 'massage therapist', 'material mover', 'materials engineer', 'materials scientist',
      'mathematical technician', 'mathematician', 'maxillofacial surgeon', 'measurer', 'meat cutter', 'meat packer', 'meat trimmer', 'mechanical drafter',
      'mechanical engineer', 'mediator', 'medical assistant', 'medical scientist', 'medical secretary', 'medical transcriptionist', 'meeting', 'meeting planner',
      'merchandise displayer', 'messenger', 'metal caster', 'metal patternmaker', 'metal pourer', 'metal worker', 'meter reader', 'microbiologist',
      'millwright', 'mining engineer', 'model', 'model maker', 'molder', 'mortician', 'motorboat mechanic', 'motorboat operator',
      'motorcycle mechanic', 'movers', 'multimedia artist', 'museum technician', 'music director', 'music teacher', 'musician', 'naval architect',
      'negotiate', 'news vendor', 'nuclear engineer', 'nuclear technician', 'nursing aide', 'nursing instructor', 'nursing teacher', 'nutritionist',
      'obstetrician', 'occupational therapist', 'offbearer', 'office', 'office clerk', 'operating engineer', 'operations manager', 'optician',
      'optometrist', 'oral surgeon', 'order clerk', 'order filler', 'orderly', 'organize', 'orthodontist', 'orthotist',
      'oven operator', 'overtime', 'painter', 'painting worker', 'paperhanger', 'paralegal', 'paramedic', 'parts salesperson',
      'payroll clerk', 'pediatrician', 'pedicurist', 'personal chef', 'personal trainer', 'pesticide applicator', 'pesticide handler', 'pesticide sprayer',
      'petroleum engineer', 'petroleum gauger', 'petroleum technician', 'pharmacist', 'pharmacy aide', 'pharmacy technician', 'philosophy teacher', 'photogrammetrist',
      'photographer', 'physical therapist', 'physician', 'physician assistant', 'physicist', 'physics teacher', 'pile-driver operator', 'pipefitter',
      'pipelayer', 'planning clerk', 'plant operator', 'plant scientist', 'plasterer', 'plastic patternmaker', 'plastic worker', 'plumber',
      'podiatrist', 'police dispatcher', 'police officer', 'political scientist', 'postmaster', 'postsecondary teacher', 'poultry cutter', 'poultry trimmer',
      'power dispatcher', 'power distributor', 'prepress technician', 'preschool teacher', 'priest', 'private detective', 'probation officer', 'procurement clerk',
      'produce', 'producer', 'product manager', 'product promoter', 'production clerk', 'production occupation', 'profession', 'professional',
      'project', 'promote', 'proofreader', 'property manager', 'prosthetist', 'prosthodontist', 'psychiatric aide', 'psychiatric technician',
      'psychiatrist', 'psychologist', 'psychology teacher', 'pump operator', 'purchasing agent', 'purchasing manager', 'qualified', 'radiation therapist',
      'radio announcer', 'radio operator', 'radiologic technician', 'radiologic technologist', 'railroad conductor', 'railroad police', 'rancher', 'receiving clerk',
      'receptionist', 'record clerk', 'recreation teacher', 'recreation worker', 'recreational therapist', 'referee', 'refrigeration installer', 'refrigeration mechanic',
      'refuse collector', 'regional planner', 'registered nurse', 'rehabilitation counselor', 'religion teacher', 'religious worker', 'rental clerk', 'repair worker',
      'reporter', 'residential advisor', 'respiratory therapist', 'responsible', 'resume', 'retail buyer', 'retail salesperson', 'retire',
      'revenue agent', 'rigger', 'rock splitter', 'roof bolter', 'roofer', 'roustabout', 'safe repairer', 'sailor',
      'salary', 'sales engineer', 'sales manager', 'sales representative', 'sampler', 'scaler', 'schedule', 'school psychologist',
      'scout leader', 'sculptor', 'secretary', 'security guard', 'segmental paver', 'semiconductor processor', 'set designer', 'shampooer',
      'shaper', 'shift', 'ship captain', 'ship engineer', 'ship loader', 'shipmate', 'shipping clerk', 'shoe worker',
      'signal operator', 'signal repairer', 'singer', 'ski patrol', 'skill', 'skincare specialist', 'slaughterer', 'slot supervisor',
      'social scientist', 'social worker', 'sociologist', 'sociology teacher', 'software developer', 'software engineer', 'soil scientist', 'solderer',
      'sorter', 'space scientist', 'speech-language pathologist', 'sports entertainer', 'sports performer', 'stationary engineer', 'statistical assistant', 'statistician',
      'steamfitter', 'stock clerk', 'stock mover', 'stonemason', 'street vendor', 'streetcar operator', 'stucco mason', 'subway operator',
      'surgeon', 'surgical technologist', 'survey researcher', 'surveying technician', 'surveyor', 'switch operator', 'switchboard operator', 'tailor',
      'taper', 'task', 'tax collector', 'tax examiner', 'tax preparer', 'taxi driver', 'teacher', 'teacher assistant',
      'team', 'team assembler', 'technical writer', 'telemarketer', 'telephone operator', 'television announcer', 'teller', 'terrazzo finisher',
      'terrazzo worker', 'tester', 'textile presser', 'textile worker', 'therapist', 'ticket agent', 'ticket taker', 'tile setter',
      'timekeeping clerk', 'tire builder', 'tire changer', 'tire repairer', 'title abstractor', 'title examiner', 'title searcher', 'tool filer',
      'tool grinder', 'tool maker', 'tool sharpener', 'tour guide', 'tower operator', 'tractor operator', 'traffic clerk', 'traffic technician',
      'transit police', 'translator', 'transportation inspector', 'transportation worker', 'trapper', 'travel agent', 'travel clerk', 'travel guide',
      'tree pruner', 'tree trimmer', 'trimmer', 'truck loader', 'truck mechanic', 'tuner', 'tutor', 'typist',
      'umpire', 'undertaker', 'unemployed', 'upholsterer', 'urban planner', 'usher', 'ux designer', 'vacation',
      'valve installer', 'veterinarian', 'veterinary assistant', 'veterinary technician', 'vocational counselor', 'wage', 'waiter', 'waitress',
      'watch repairer', 'web developer', 'weigher', 'welder', 'wellhead pumper', 'wholesale buyer', 'wildlife biologist', 'window trimmer',
      'wood patternmaker', 'woodworker', 'word processor', 'work', 'writer', 'yardmaster', 'zoologist',
    ],
  },
  {
    slug: 'travel',
    title: 'Путешествия',
    description: 'Туризм, направления, бронирование',
    iconName: 'AirplaneTakeOff01Icon',
    sortOrder: 8,
    words: [
      'abroad', 'adventure', 'airport', 'arctic', 'arrival', 'arrive', 'backpack', 'beach',
      'book', 'border', 'camp', 'cancel', 'castle', 'cathedral', 'cave', 'cliff',
      'coast', 'continent', 'cruise', 'customs', 'delay', 'depart', 'departure', 'desert',
      'destination', 'embassy', 'equator', 'excursion', 'explore', 'flight', 'foreign', 'forest',
      'glacier', 'guide', 'hemisphere', 'holiday', 'hostel', 'hotel', 'immigration', 'island',
      'itinerary', 'journey', 'lake', 'landmark', 'landscape', 'layover', 'luggage', 'map',
      'monument', 'mountain', 'ocean', 'passport', 'peninsula', 'photograph', 'reservation', 'resort',
      'river', 'ruins', 'scenery', 'sea', 'sightseeing', 'souvenir', 'suitcase', 'temple',
      'ticket', 'tourist', 'transit', 'travel', 'trip', 'tropical', 'vacation', 'visa',
      'waterfall',
    ],
  },
  {
    slug: 'sport',
    title: 'Спорт и фитнес',
    description: 'Виды спорта, тренировки, соревнования',
    iconName: 'WorkoutRunIcon',
    sortOrder: 9,
    words: [
      'abseiling', 'acro sports', 'acrobatic gymnastics', 'aerobatics', 'aerobic gymnastics', 'aid climbing', 'aiki-jūjutsu', 'aikido',
      'air hockey', 'air racing', 'air sports', 'airsoft', 'aizkolaritza', 'alpine skiing', 'amateur wrestling', 'american football',
      'american handball', 'angling', 'apnoea finswimming', 'aquathlon', 'archery', 'arena football', 'arm wrestling', 'artistic billiards',
      'artistic cycling', 'artistic gymnastics', 'artistic pool', 'association football', 'athlete', 'atv racing', 'australian football', 'australian handball',
      'austus', 'auto race', 'auto racing', 'autocross', 'autograss', 'axe throwing', 'ba game', 'backgammon',
      'backpacking', 'backstroke', 'badminton', 'bagatelle', 'baguazhang', 'balance beam', 'ball', 'ball badminton',
      'ball hockey', 'ball-over-net games', 'bando', 'bandy', 'banger racing', 'bank pool', 'banzai skydiving', 'bar billiards',
      'barrel jumping', 'barrel racing', 'bartitsu', 'base jumping', 'baseball', 'basketball', 'basque pelota', 'baton twirling',
      'battōjutsu', 'beach basketball', 'beach handball', 'beach rugby', 'beach soccer', 'beach tennis', 'beach volleyball', 'beagling',
      'beer pong', 'benchrest shooting', 'biathlon', 'bicycle polo', 'bifins', 'big-game fishing', 'biribol', 'blackball',
      'bmx', 'board sports', 'bobsleigh', 'bocce', 'bocce volo', 'boccia', 'bodyboarding', 'bodybuilding',
      'boffer fighting', 'bokator', 'bolas criollas', 'boli khela', 'bossaball', 'bottle pool', 'bouldering', 'boule lyonnaise',
      'boules', 'bowling', 'bowlliards', 'bowls', 'box lacrosse', 'boxing', 'brazilian jiu-jitsu', 'breakaway roping',
      'breaststroke', 'british baseball', 'british bulldogs', 'bronc riding', 'broomball', 'brännboll', 'bujinkan', 'bullriding',
      'bumper pool', 'bungee jumping', 'bunnock', 'bushwhacking', 'butterfly stroke', 'butts up', 'buzkashi', 'caid',
      'calcio fiorentino', 'calf roping', 'calva', 'calvinball', 'cammag', 'camogie', 'campdrafting', 'canadian football',
      'canoe polo', 'canoeing', 'canyoning', 'capoeira', 'card stacking', 'carom billiards', 'casterboarding', 'casting',
      'catch', 'catch games', 'catch wrestling', 'cestoball', 'champion', 'championship', 'chariot racing', 'charreada',
      'checkers', 'cheerleading', 'chess boxing', 'chicago', 'chilean rodeo', 'chinese handball', 'chinlone', 'choi kwang-do',
      'cirit', 'cliff diving', 'climbing', 'club', 'cluster ballooning', 'cnapan', 'coach', 'coasteering',
      'cockfighting', 'collar-and-elbow', 'competition', 'competitive dancing', 'competitive eating', 'competitive swimming', 'connect four', 'cornhole',
      'cornish hurling', 'cornish wrestling', 'court', 'cowboy', 'cowboy polo', 'creeking', 'cribbage', 'cricket',
      'croquet', 'cross country', 'cross-country rally', 'cross-country running', 'cross-country skiing', 'crossfit', 'cue sports', 'cuju',
      'curling', 'cushion caroms', 'cutthroat', 'cutting', 'cycle polo', 'cycle speedway', 'cycling', 'cyclo-cross',
      'czech handball', 'dancesport', 'danish longball', 'darts', 'deaf basketball', 'decathlon', 'deep-water soloing', 'deer hunting',
      'defeat', 'demolition derby', 'desert racing', 'dice stacking', 'dinghy sailing', 'dirt jumping', 'disc dog', 'disc golf',
      'discus', 'diving', 'dodge disc', 'dodgeball', 'dominoes', 'drag racing', 'draw', 'dressage',
      'dribble', 'drifting', 'duathlon', 'dumog', 'eclipse ball', 'eight-ball', 'eight-man football', 'ekiden',
      'elephant polo', 'elle', 'endurance racing', 'endurance riding', 'enduro', 'energy', 'english billiards', 'english pleasure',
      'episkyros', 'equestrian vaulting', 'equitation', 'eskrima', 'eton college', 'eton fives', 'eventing', 'exercise',
      'extreme ironing', 'fan', 'fast-pitch softball', 'fastnet', 'fell running', 'fencing', 'ferret legging', 'field',
      'field archery', 'field game', 'field handball', 'field hockey', 'field lacrosse', 'field target', 'fierljeppen', 'figure skating',
      'fishing', 'fistball', 'fitness', 'five-a-side football', 'five-pins', 'fives', 'flag football', 'flight archery',
      'floor', 'floorball', 'flutterguts', 'fly fishing', 'flyak', 'flying trapeze', 'folk wrestling', 'folkrace',
      'foosball', 'footbag', 'footbag net', 'football', 'football tennis', 'footvolley', 'formula libre', 'formula racing',
      'formula student', 'foul', 'four square', 'four-ball', 'fox hunting', 'free running', 'free-style moto', 'freeboard',
      'freeboating', 'freediving', 'freestyle', 'freestyle bmx', 'freestyle footbag', 'freestyle football', 'freestyle motocross', 'freestyle skiing',
      'freestyle swimming', 'freestyle wrestling', 'frisian handball', 'frontenis', 'futsal', 'ga-ga', 'gaelic football', 'gaelic handball',
      'game', 'gateball', 'gatka', 'geocaching', 'gig racing', 'gliding', 'glima', 'goal',
      'goalball', 'goaltimate', 'goat tying', 'golf', 'gouren', 'grappling', 'grasstrack', 'greco-roman wrestling',
      'greek wrestling', 'gridiron football', 'gungdo', 'guts', 'gym', 'gymkhana', 'gymnastics', 'haggis hurling',
      'half marathon', 'hammer throw', 'handball', 'hang gliding', 'hapkido', 'hardball squash', 'hare coursing', 'harness racing',
      'harpastum', 'harrow football', 'haxey hood', 'headis', 'heptathlon', 'high bar', 'high jump', 'highland games',
      'hiking', 'hillclimbing', 'hockey', 'hojōjutsu', 'hoop', 'hooverball', 'hopper ballooning', 'hornussen',
      'horse polo', 'horse racing', 'horseball', 'horseshoe', 'horseshoe throwing', 'horseshoes', 'hot box', 'hunter',
      'hunter-jumpers', 'hurdles', 'hurling', 'hybrid codes', 'hydroplane racing', 'iaidō', 'iaijutsu', 'ice climbing',
      'ice dancing', 'ice fishing', 'ice hockey', 'ice racing', 'ice speedway', 'ice sports', 'ice yachting', 'icosathlon',
      'immersion finswimming', 'individual medley', 'indoor archery', 'indoor cricket', 'indoor enduro', 'indoor football', 'indoor netball', 'indoor soccer',
      'injury', 'inline hockey', 'intercrosse', 'international fronton', 'jai alai', 'janggi', 'javelin', 'jeu provençal',
      'jianzi', 'jittejutsu', 'jorkyball', 'jousting', 'judo', 'jugger', 'juggling', 'jujutsu',
      'jump', 'jumping', 'jōdō', 'jūkendō', 'kabaddi', 'kajukenbo', 'kalaripayattu', 'karate',
      'kart racing', 'kayaking', 'keep away', 'keepie uppie', 'kelly pool', 'kemari', 'kendo', 'kenjutsu',
      'kenpō', 'kho kho', 'ki-o-rahi', 'kick', 'kickball', 'kickboxing', 'kilikiti', 'killer',
      'kin-ball', 'kindred activities', 'kite buggy', 'kite fighting', 'kite flying', 'kite landboarding', 'kite sports', 'kiteboarding',
      'kitesurfing', 'knattleikr', 'kneeboarding', 'knife throwing', 'korfball', 'krabi–krabong', 'krav maga', 'kubb',
      'kumdo', 'kung fu', 'kurash', 'kyūdō', 'kyūjutsu', 'la soule', 'lacrosse', 'lancashire wrestling',
      'land sailing', 'land windsurfing', 'laser tag', 'league', 'lelo burti', 'lethwei', 'letterboxing', 'logrolling',
      'long jump', 'longboarding', 'lose', 'luge', 'lumberjack sports', 'mahjong', 'malla-yuddha', 'marathon',
      'marching band', 'marn grook', 'masters football', 'matball', 'match', 'match play', 'matkot', 'medal',
      'medieval football', 'medley relay', 'mesoamerican ballgame', 'metallic silhouette', 'metro footy', 'mini rugby', 'miniature golf', 'miniten',
      'mixed climbing', 'mob football', 'mod league', 'model aerobatics', 'model aircraft', 'modern arnis', 'modern pentathlon', 'mongolian wrestling',
      'monster truck', 'moscow broomball', 'motocross', 'motorboat racing', 'motorcycle racing', 'motorcycle speedway', 'motorized sports', 'mountain running',
      'mountain unicycling', 'mountainboarding', 'mountaineering', 'muay thai', 'mud bogging', 'mölkky', 'naginatajutsu', 'netball',
      'newcomb ball', 'nguni stick-fighting', 'nine-a-side footy', 'nine-ball', 'nine-man football', 'ninjutsu', 'noodling', 'nordic combined',
      'nordic skiing', 'novuss', 'object spinning', 'obstacle variations', 'off-road racing', 'off-roading', 'oina', 'okinawan kobudō',
      'olympic', 'olympic weightlifting', 'one-pocket', 'opponent', 'orienteering', 'outrigger canoeing', 'oztag', 'paddleboarding',
      'padel', 'padiddling', 'paintball', 'pair skating', 'palant', 'paleta frontón', 'pall mall', 'palla',
      'pankration', 'papi fut', 'parachuting', 'paragliding', 'parallel bars', 'paralympic football', 'paralympic volleyball', 'paramotoring',
      'parasailing', 'parkour', 'pass', 'patball', 'pato', 'pehlwani', 'pelota mixteca', 'penalty',
      'pencak silat', 'pentathlon', 'peteca', 'pickleball', 'plate spinning', 'platform tennis', 'play', 'player',
      'pocket billiards', 'point', 'pole bending', 'pole climbing', 'pole vault', 'polo', 'polocrosse', 'pommel horse',
      'pond hockey', 'pool', 'popinjay', 'power hockey', 'powerbocking', 'powerchair football', 'powered paragliding', 'powerlifting',
      'practical shooting', 'practice', 'pradal serey', 'professional wrestling', 'punchball', 'pétanque', 'qianball', 'quidditch',
      'race', 'racewalking', 'racketlon', 'racquetball', 'racquets', 'rafting', 'rally raid', 'rallycross',
      'rallying', 'rc racing', 'real tennis', 'rec footy', 'record', 'red rover', 'reduced variants', 'referee',
      'regularity rally', 'reining', 'relay', 'remote control', 'reversi', 'rhythmic gymnastics', 'ribbon', 'ring-goal',
      'ringball', 'ringette', 'rink bandy', 'rinkball', 'riverboarding', 'road racing', 'road running', 'robot combat',
      'rocball', 'rock climbing', 'rock fishing', 'rocket league', 'rodeo', 'rogaining', 'roller hockey', 'rope',
      'rope climbing', 'rope jumping', 'roping', 'rossall hockey', 'rotation', 'rounders', 'rowing', 'rugby fives',
      'rugby football', 'rugby league', 'rugby sevens', 'rugby tens', 'rugby union', 'running', 'russian pyramid', 'sack race',
      'sailing', 'samoa rules', 'sandboarding', 'sanshou', 'savate', 'schwingen', 'scootering', 'score',
      'scrabble', 'scrub baseball', 'scuba diving', 'sea kayaking', 'segway polo', 'sepak takraw', 'seven-ball', 'shidōkan karate',
      'shinty', 'shogi', 'shoot boxing', 'shootfighting', 'shooting', 'shorinji kempo', 'shot put', 'shotgun start',
      'show jumping', 'shuai jiao', 'shuffleboard', 'shurikenjutsu', 'shōrin-ryū shidōkan', 'sikaran', 'silambam', 'silat',
      'single scull', 'single skating', 'sinuca brasileira', 'sipa', 'six-man football', 'six-red snooker', 'skateboarding', 'skater hockey',
      'skee ball', 'skeet shooting', 'skeleton', 'ski flying', 'ski jumping', 'ski touring', 'skiboarding', 'skibob',
      'skibobbing', 'skiing', 'skijoring', 'skimboarding', 'skins game', 'skirmish', 'skittles', 'skydiving',
      'skyrunning', 'skysurfing', 'slacklining', 'slamball', 'sledge hockey', 'slow pitch', 'snooker', 'snooker plus',
      'snorkelling', 'snow kiting', 'snow rugby', 'snow sports', 'snowboarding', 'snowkiting', 'snowmobile racing', 'snowshoe running',
      'soap shoes', 'soft tennis', 'softball', 'spearfishing', 'speed', 'speed golf', 'speed pool', 'speed skiing',
      'speed-ball', 'speedball', 'speedminton', 'spongee', 'sport', 'sport climbing', 'sport diving', 'sport fishing',
      'sport kite', 'sport stacking', 'sporting clays', 'sprint', 'sprint football', 'squash', 'squash tennis', 'squirt boating',
      'ssireum', 'stacking', 'stadium', 'static trapeze', 'steeplechase', 'steer roping', 'steer wrestling', 'steinstossen',
      'stickball', 'stické', 'still rings', 'stool ball', 'straight pool', 'street football', 'street hockey', 'street racing',
      'street sports', 'street unicycling', 'street workout', 'streetball', 'streetboarding', 'streetluge', 'strength', 'strength athletics',
      'stretch', 'striking', 'stroke play', 'strongman', 'subak', 'subbuteo', 'sumo', 'superbike racing',
      'supercross', 'supermoto', 'superside', 'supersport racing', 'sur-papakh', 'surf fishing', 'surf kayaking', 'surface finswimming',
      'surfboat', 'surfing', 'swamp football', 'swimming', 'sword fighting', 'synchronized swimming', 'systema', 'sōjutsu',
      'table football', 'table hockey', 'table sports', 'table tennis', 'tackle', 'taekkyeon', 'taekwondo', 'tag',
      'tag games', 'tag rugby', 'taidō', 'target archery', 'target shooting', 'tchoukball', 'team', 'team handball',
      'team penning', 'team play', 'team roping', 'tee-ball', 'telemark skiing', 'ten-ball', 'tennikoit', 'tennis',
      'tennis polo', 'tent pegging', 'test cricket', 'tetherball', 'tetrathlon', 'three-ball', 'three-cushion', 'three-legged race',
      'throw', 'throwball', 'throwing', 'thumb wrestling', 'time attack', 'toboggan', 'toe wrestling', 'torball',
      'touch football', 'touch rugby', 'tournament', 'tower running', 'town ball', 'track cycling', 'track racing', 'tractor pulling',
      'traditional climbing', 'trail running', 'train', 'trampolining', 'trap shooting', 'trapeze', 'trial', 'triathlon',
      'triple jump', 'truck racing', 'trugo', 'tt racing', 'tug-o-war', 'tumbling', 'ultimate', 'ultralight aviation',
      'ultramarathon', 'underwater cycling', 'underwater football', 'underwater hockey', 'underwater orienteering', 'underwater photography', 'underwater rugby', 'underwater wrestling',
      'uneven bars', 'unicycle', 'unicycle basketball', 'unicycle hockey', 'unicycle trials', 'unicycling', 'universal football', 'urban golf',
      'vajra-mushti', 'vale tudo', 'valencian frontó', 'valencian pilota', 'varzesh-e pahlavani', 'vault', 'victory', 'vigoro',
      'vintage racing', 'volata', 'volleyball', 'vovinam', 'wakeboarding', 'wakesurfing', 'walking', 'wall game',
      'wall-and-ball', 'wallball', 'wallyball', 'warm-up', 'water basketball', 'water polo', 'water volleyball', 'waymarking',
      'weightlifting', 'western pleasure', 'wheelchair basketball', 'wheelchair racing', 'wheelstand competition', 'whitewater kayaking', 'wife-carrying', 'wiffleball',
      'win', 'windsurfing', 'wing chun', 'wingsuit flying', 'wireball', 'woggabaliri', 'wolf hunting', 'women\'s lacrosse',
      'wood chopping', 'wood splitting', 'woodball', 'woodsman', 'wrestling', 'wushu', 'xare', 'xiangqi',
      'yak polo', 'yağlı güreş', 'yoyoing', 'yubi lakpi', 'yukigassen', 'zourkhaneh',
    ],
  },
  {
    slug: 'weather-nature',
    title: 'Погода и природа',
    description: 'Погодные явления, природные объекты, климат',
    iconName: 'Sun03Icon',
    sortOrder: 10,
    words: [
      'amaranth', 'amaryllis', 'anemone', 'aster', 'autumn', 'azalea', 'babys breath', 'bark',
      'begonia', 'bellflower', 'bergamot', 'blizzard', 'bloom', 'blossom', 'bluebell', 'bottlebrush',
      'branch', 'breeze', 'bush', 'buttercup', 'camellias', 'carnation', 'chrysantemum', 'climate',
      'cloud', 'clover', 'cold', 'columbine', 'cool', 'crocus', 'crop', 'daffodil',
      'dahlia', 'daisy', 'dawn', 'delphinium', 'dew', 'drought', 'dry', 'dusk',
      'earth', 'earthquake', 'edelweiss', 'environment', 'field', 'flood', 'flower', 'fog',
      'forest', 'foxglove', 'freesia', 'freeze', 'frost', 'gerbera daisy', 'gladiolus', 'grass',
      'grow', 'gust', 'habitat', 'hail', 'harvest', 'heather', 'hibiscus', 'hill',
      'holly', 'hot', 'hurricane', 'hyacinth', 'ice', 'iris', 'jasmine', 'jungle',
      'ladys slipper', 'lake', 'lavender', 'leaf', 'lightning', 'lilac', 'lily', 'lotus flower',
      'marigold', 'marjoram', 'marsh', 'meadow', 'melt', 'mimosa', 'moon', 'moss',
      'mountain', 'narcissus', 'nature', 'ocean', 'orange blossom', 'orchid', 'peach blossom', 'peony',
      'petunia', 'plant', 'pollen', 'pollution', 'pond', 'primrose', 'rain', 'rainbow',
      'rhododendron', 'river', 'rock', 'root', 'rosemary', 'roses', 'sage', 'sand',
      'sea', 'season', 'seed', 'shade', 'shadow', 'shore', 'sky', 'snapdragon',
      'snow', 'soil', 'species', 'spring', 'star', 'stone', 'storm', 'stream',
      'summer', 'sun', 'sunflower', 'sunrise', 'sunset', 'swamp', 'tansy', 'temperature',
      'thistle', 'thorn', 'thunder', 'thyme', 'tornado', 'tree', 'trunk', 'tulip',
      'valley', 'vine', 'violet', 'volcano', 'warm', 'water lily', 'wave', 'weather',
      'weed', 'wet', 'wilderness', 'wind', 'winter', 'zinnia',
    ],
  },
  {
    slug: 'transport',
    title: 'Транспорт',
    description: 'Виды транспорта, дорожное движение, поездки',
    iconName: 'Car01Icon',
    sortOrder: 11,
    words: [
      'accident', 'ambulance', 'belt', 'bicycle', 'boat', 'bridge', 'bus', 'car',
      'cargo', 'carriage', 'commute', 'crosswalk', 'direction', 'dock', 'drive', 'driver',
      'engine', 'ferry', 'fly', 'freight', 'fuel', 'garage', 'harbor', 'helicopter',
      'highway', 'intersection', 'lane', 'license', 'map', 'motorcycle', 'park', 'passenger',
      'pedestrian', 'pilot', 'plane', 'platform', 'port', 'ride', 'road', 'roundabout',
      'route', 'runway', 'sail', 'scooter', 'seat', 'ship', 'sidewalk', 'speed',
      'station', 'stop', 'street', 'subway', 'taxi', 'terminal', 'ticket', 'tire',
      'tractor', 'traffic', 'train', 'tram', 'truck', 'tunnel', 'van', 'wagon',
      'wheel',
    ],
  },
  {
    slug: 'education',
    title: 'Образование',
    description: 'Учёба, школа, университет, знания',
    iconName: 'MortarboardIcon',
    sortOrder: 12,
    words: [
      'academic', 'assignment', 'board', 'book', 'calculate', 'campus', 'certificate', 'chapter',
      'class', 'college', 'count', 'course', 'curriculum', 'dean', 'degree', 'dictionary',
      'diploma', 'discipline', 'dissertation', 'dormitory', 'education', 'encyclopedia', 'essay', 'exam',
      'experiment', 'faculty', 'fluent', 'geography', 'grade', 'graduate', 'grammar', 'history',
      'homework', 'kindergarten', 'knowledge', 'laboratory', 'language', 'learn', 'lecture', 'lesson',
      'library', 'literature', 'mark', 'math', 'notebook', 'nursery', 'paragraph', 'pen',
      'pencil', 'principal', 'professor', 'pronunciation', 'pupil', 'read', 'research', 'scholar',
      'scholarship', 'school', 'science', 'seminar', 'sentence', 'skill', 'spelling', 'student',
      'study', 'subject', 'teach', 'teacher', 'test', 'textbook', 'thesis', 'tuition',
      'university', 'vocabulary', 'write',
    ],
  },
  {
    slug: 'emotions',
    title: 'Эмоции и чувства',
    description: 'Чувства, настроение, эмоциональные состояния',
    iconName: 'SmileFaceIcon',
    sortOrder: 13,
    words: [
      'abandoned', 'absent minded', 'abused', 'accepted', 'accomplished', 'accusatory', 'accused', 'admired',
      'adored', 'adrift', 'affectionate', 'afraid', 'aggravated', 'aggressive', 'agitated', 'alarmed',
      'alert', 'alienated', 'alive', 'alluring', 'alone', 'aloof', 'amazed', 'ambushed',
      'amused', 'anger', 'angry', 'annoyed', 'antagonistic', 'anxious', 'apathetic', 'apologetic',
      'appalled', 'appreciated', 'appreciative', 'apprehensive', 'aroused', 'ashamed', 'astonished', 'attacked',
      'attractive', 'awake', 'aware', 'awe', 'awed', 'awestruck', 'awkward', 'bad',
      'baffled', 'barren', 'bashful', 'beaten', 'belittled', 'benevolent', 'berated', 'betrayed',
      'bewildered', 'bitchy', 'bitter', 'bittersweet', 'blah', 'blamed', 'blank', 'blissful',
      'blue', 'bold', 'bored', 'bothered', 'bouncy', 'brave', 'broken', 'brooding',
      'bummed', 'burdened', 'burned-out', 'callous', 'calm', 'capable', 'carefree', 'careless',
      'caring', 'caustic', 'cautious', 'censored', 'centered', 'certain', 'challenged', 'charmed',
      'cheated', 'cheerful', 'cherished', 'childish', 'chipper', 'choleric', 'clean', 'clear',
      'clever', 'close', 'closed', 'clueless', 'clumsy', 'cold', 'comfort', 'comfortable',
      'committed', 'compassionate', 'competent', 'competitive', 'complacent', 'complete', 'concerned', 'condemned',
      'condescension', 'confident', 'confining', 'confused', 'considerate', 'contemplative', 'contempt', 'contemptuous',
      'content', 'control', 'controlled', 'conventional', 'convicted', 'cornered', 'courageous', 'cowardly',
      'cranky', 'crappy', 'crazy', 'critical', 'cross', 'crushed', 'cry', 'curious',
      'cynical', 'daring', 'dark', 'dashed', 'dazed', 'dead', 'deceived', 'dedicated',
      'defeated', 'defenseless', 'defensive', 'defiant', 'degraded', 'dejected', 'delicate', 'delighted',
      'demoralized', 'dependent', 'depressed', 'deprived', 'derisive', 'deserted', 'desired', 'desolate',
      'despair', 'desperate', 'destroyed', 'detached', 'determined', 'devastated', 'devious', 'devoted',
      'didactic', 'different', 'difficult', 'dignified', 'dirty', 'disappointed', 'disbelieving', 'discarded',
      'disconnected', 'discontent', 'discontented', 'discouraged', 'disdainful', 'disgraced', 'disgusted', 'disheartened',
      'dishonest', 'disillusioned', 'dismal', 'dismayed', 'disobedient', 'disorganized', 'disposable', 'distant',
      'distracted', 'distressed', 'disturbed', 'ditzy', 'dorky', 'doubtful', 'down', 'drained',
      'dreamy', 'dreary', 'dropped', 'drunk', 'dull', 'dumb', 'eager', 'earnest',
      'ecstatic', 'edgy', 'effective', 'elated', 'embarassed', 'embarrassed', 'emotion', 'empathetic',
      'empowered', 'empty', 'enchanted', 'encouraged', 'energetic', 'energized', 'enlightened', 'enraged',
      'enriched', 'entertained', 'enthralled', 'enthusiastic', 'envious', 'erudite', 'evasive', 'evil',
      'exasperated', 'excited', 'excluded', 'exhausted', 'exhilarated', 'expectant', 'exploited', 'exposed',
      'exuberant', 'fact', 'faithful', 'fake', 'fanciful', 'fantastic', 'fatalistic', 'fatigued',
      'fear', 'fearful', 'fearless', 'feel', 'feeling', 'feisty', 'fine', 'flirty',
      'flustered', 'foolish', 'foreboding', 'forgiven', 'forgiving', 'forgotten', 'forthright', 'fortunate',
      'framed', 'frantic', 'free', 'friendly', 'frightened', 'frisky', 'frustrated', 'fulfilled',
      'full', 'funny', 'furious', 'futile', 'geeky', 'generous', 'gentle', 'giddy',
      'giggly', 'giving', 'glad', 'gloomy', 'glorious', 'good', 'grateful', 'great',
      'grief', 'grieving', 'groggy', 'grouchy', 'grumpy', 'guarded', 'guilty', 'gullible',
      'handicapped', 'happy', 'harmonious', 'hate', 'hateful', 'haughty', 'haunted', 'haunting',
      'healthy', 'heard', 'heartbroken', 'heavy-hearted', 'helpful', 'helpless', 'hesitant', 'high',
      'honored', 'hopeful', 'hopeless', 'horrible', 'horrified', 'hospitable', 'hostile', 'hot',
      'humble', 'humiliated', 'hungry', 'hurt', 'hyper', 'hysterical', 'idealistic', 'idiotic',
      'idyllic', 'ignorant', 'ignored', 'imaginative', 'immune', 'impatient', 'impelled', 'imperfect',
      'impertinent', 'important', 'impressed', 'impulsive', 'inadequate', 'inattentive', 'incensed', 'inclusive',
      'incompetent', 'incomplete', 'incredulous', 'indebted', 'indecisive', 'independent', 'indescribable', 'indifferent',
      'indignant', 'industrious', 'inept', 'inferior', 'inflated', 'informed', 'infuriated', 'inhibited',
      'innocent', 'innovative', 'inquisitive', 'insane', 'insecure', 'insensitive', 'insidious', 'insignificant',
      'insulted', 'intense', 'interested', 'interrogated', 'interrupted', 'intimate', 'intimidated', 'intrigued',
      'invigorated', 'invisible', 'involved', 'irate', 'irked', 'irrational', 'irresponsible', 'irritated',
      'isolated', 'jaded', 'jealous', 'jinxed', 'jolly', 'jovial', 'joy', 'joyful',
      'joyous', 'jubilant', 'judged', 'judgmental', 'jumpy', 'just', 'justified', 'kidded',
      'kind', 'knowledgeable', 'late', 'laugh', 'lazy', 'leery', 'left', 'let',
      'lethargic', 'liable', 'liberated', 'liberating', 'lifeless', 'light-hearted', 'liked', 'listened',
      'listless', 'logical', 'lonely', 'loose', 'lost', 'lousy', 'lovable', 'love',
      'loved', 'loving', 'lucky', 'lyrical', 'mad', 'malicious', 'manipulated', 'matter',
      'mean', 'meditative', 'melancholic', 'melancholy', 'mellow', 'merciless', 'merry', 'mischievous',
      'miserable', 'misinterpreted', 'mistreated', 'misunderstood', 'mixed', 'mocked', 'mocking', 'modest',
      'molested', 'mood', 'moody', 'morose', 'motivated', 'mournful', 'moved', 'mystified',
      'naive', 'nasty', 'naughty', 'nauseated', 'needed', 'needy', 'negative', 'neglected',
      'nerdy', 'nervous', 'neurotic', 'nightmarish', 'nonchalant', 'nostalgic', 'not', 'noticed',
      'numb', 'obeyed', 'objective', 'obligated', 'obvious', 'odd', 'off', 'offended',
      'okay', 'old', 'open', 'oppressed', 'optimistic', 'ornery', 'outraged', 'overcome',
      'overjoyed', 'overloaded', 'overwhelmed', 'overworked', 'owned', 'pain', 'painful', 'pampered',
      'panicky', 'paralyzed', 'passionate', 'passive', 'patient', 'patronizing', 'peaceful', 'peeved',
      'pensive', 'perky', 'perplexed', 'persecuted', 'pessimistic', 'pestered', 'petrified', 'petty',
      'phony', 'pious', 'pissed', 'playful', 'pleased', 'pleasure', 'poor', 'positive',
      'possessive', 'powerful', 'powerless', 'practical', 'predatory', 'pressured', 'private', 'productive',
      'protected', 'protective', 'proud', 'provoked', 'prudish', 'punished', 'pushy', 'puzzled',
      'questioned', 'quiet', 'quixotic', 'quizzical', 'rambunctious', 'realistic', 'reassured', 'rebellious',
      'reborn', 'receptive', 'reckless', 'recognized', 'reconciled', 'recumbent', 'reflective', 'refreshed',
      'regretful', 'rejected', 'rejuvenated', 'relaxed', 'released', 'relieved', 'reluctant', 'reminiscent',
      'remorse', 'renewed', 'replaced', 'replenished', 'repressed', 'rescued', 'resentful', 'reserved',
      'resistant', 'resourceful', 'respected', 'responsible', 'restless', 'restricted', 'revengeful', 'reverent',
      'revitalized', 'ribald', 'rich', 'ridicule', 'ridiculous', 'right', 'rigid', 'robbed',
      'romantic', 'rotten', 'rushed', 'sabotaged', 'sad', 'safe', 'sarcastic', 'sardonic',
      'sassy', 'satiated', 'satiric', 'satisfied', 'saved', 'scared', 'scolded', 'scorned',
      'scream', 'secure', 'seductive', 'self-assured', 'self-centered', 'self-confident', 'self-conscious', 'self-destructive',
      'self-reliant', 'selfish', 'sensitive', 'sentimental', 'serene', 'serious', 'sexy', 'shaken',
      'shamed', 'sheepish', 'shiver', 'shocked', 'shunned', 'shy', 'sick', 'sigh',
      'silenced', 'silly', 'sincere', 'sinful', 'skeptical', 'skillful', 'slandered', 'sleepy',
      'sluggish', 'small', 'smart', 'smile', 'smothered', 'solemn', 'somber', 'soothed',
      'sorrow', 'sorry', 'special', 'specified', 'spiteful', 'splendid', 'spunky', 'squashed',
      'stifled', 'stimulated', 'stingy', 'strained', 'stressed', 'stretched', 'strong', 'stubborn',
      'stumped', 'stunned', 'stupid', 'submissive', 'successful', 'suffer', 'suffocated', 'suicidal',
      'sullen', 'sunk', 'super', 'superior', 'supported', 'sure', 'surly', 'surprised',
      'suspenseful', 'suspicious', 'sympathetic', 'tacky', 'tactful', 'talented', 'talkative', 'tame',
      'tarnished', 'tasteful', 'tearful', 'teased', 'tenacious', 'tender', 'tense', 'tepid',
      'terrible', 'terrific', 'terrified', 'terrifying', 'tested', 'testy', 'thankful', 'thoughtful',
      'threatened', 'threatening', 'thrifty', 'thrilled', 'tired', 'tormented', 'torn', 'tortured',
      'touched', 'tough', 'tragic', 'tranquil', 'transformed', 'trapped', 'treasured', 'tremble',
      'trembly', 'tremendous', 'tricked', 'troubled', 'trusted', 'trustful', 'ugly', 'unaccepted',
      'unappreciated', 'unbalanced', 'unburdened', 'uncanny', 'uncomfortable', 'unconcerned', 'uneven', 'unfit',
      'unfriendly', 'united', 'unjust', 'unknown', 'unneeded', 'unpleasant', 'unreal', 'unruly',
      'unwise', 'up', 'uplifted', 'used', 'useless', 'vacant', 'vague', 'vain',
      'valid', 'valued', 'vengeful', 'vexed', 'vicious', 'victimized', 'victorious', 'violated',
      'violent', 'vivacious', 'vivid', 'void', 'wacky', 'warlike', 'warm', 'warmhearted',
      'warned', 'wary', 'wasted', 'weak', 'wealthy', 'weary', 'weird', 'welcoming',
      'whimsical', 'whisper', 'whole', 'wild', 'willful', 'wishful', 'witty', 'worldly',
      'worried', 'worse', 'worthy', 'wounded', 'wrong', 'yearning', 'yellow', 'yielding',
      'young', 'youthful', 'zany', 'zealous',
    ],
  },
  {
    slug: 'technology',
    title: 'Технологии',
    description: 'Компьютеры, интернет, гаджеты, программирование',
    iconName: 'Laptop01Icon',
    sortOrder: 14,
    words: [
      'account', 'air conditioner', 'air fryer', 'air ioniser', 'algorithm', 'app', 'aroma lamp', 'artificial',
      'attic fan', 'automation', 'bachelor griller', 'back boiler', 'backup', 'barbecue', 'battery', 'beehive oven',
      'beverage opener', 'bluetooth', 'boiler', 'bread machine', 'broadcast', 'bug', 'butane torch', 'cable',
      'camera', 'can opener', 'ceiling fan', 'charge', 'chip', 'click', 'clothes dryer', 'clothes iron',
      'cloud', 'code', 'coffee percolator', 'coffeemaker', 'compactor', 'computer', 'connect', 'convection heater',
      'convection microwave', 'convection oven', 'corn roaster', 'crash', 'crepe maker', 'data', 'database', 'deep fryer',
      'dehumidifier', 'delete', 'device', 'digital', 'dishwasher', 'download', 'drone', 'earth oven',
      'electric cooker', 'email', 'embroidery machine', 'encryption', 'energy regulator', 'espresso machine', 'fan heater', 'field kitchen',
      'file', 'fire pot', 'fireplace toaster', 'firewall', 'flattop grill', 'folder', 'food steamer', 'format',
      'hack', 'hair dryer', 'hair iron', 'halogen oven', 'hardware', 'headphones', 'home server', 'hot plate',
      'humidifier', 'hvac', 'icebox', 'innovation', 'install', 'intelligence', 'internet', 'internet refrigerator',
      'kettle', 'keyboard', 'kimchi refrigerator', 'kitchener range', 'laser', 'memory', 'message', 'micathermic heater',
      'microphone', 'microwave oven', 'monitor', 'mouse', 'mousetrap', 'network', 'oil heater', 'online',
      'oven', 'password', 'patio heater', 'phone', 'pixel', 'plug', 'pneumatic vacuum', 'popcorn maker',
      'pressure cooker', 'pressure fryer', 'printer', 'processor', 'program', 'radiator', 'reflector oven', 'refrigerator',
      'resolution', 'restore', 'rice cooker', 'rice polisher', 'robot', 'rotisserie', 'sandwich toaster', 'satellite',
      'scan', 'screen', 'search', 'self-cleaning oven', 'sensor', 'server', 'set-n-forget cooker', 'sewing machine',
      'signal', 'slow cooker', 'socket', 'software', 'solar cooker', 'sous-vide cooker', 'speaker', 'stove',
      'stream', 'sump pump', 'susceptor', 'swamp cooler', 'switch', 'system', 'tandoor', 'technology',
      'tie press', 'toaster', 'toaster oven', 'trivet', 'trouser press', 'turkey fryer', 'type', 'update',
      'upload', 'vacuum cleaner', 'vacuum fryer', 'vaporizer', 'virtual', 'virus', 'waffle iron', 'washing machine',
      'water cooker', 'water cooler', 'water heater', 'website', 'wet grinder', 'window fan', 'wireless', 'wood-fired oven',
    ],
  },
  {
    slug: 'city',
    title: 'Город',
    description: 'Городская жизнь, места, инфраструктура',
    iconName: 'Building01Icon',
    sortOrder: 15,
    words: [
      'alley', 'apartment', 'aquarium', 'area', 'arena', 'avenue', 'bank', 'bar',
      'bench', 'billboard', 'boulevard', 'bridge', 'building', 'bus stop', 'cafe', 'cathedral',
      'cemetery', 'church', 'cinema', 'city', 'courthouse', 'crosswalk', 'crowd', 'district',
      'downtown', 'embassy', 'factory', 'fence', 'fire station', 'fountain', 'gallery', 'graffiti',
      'harbor', 'highway', 'hospital', 'lamp', 'library', 'mall', 'market', 'monument',
      'museum', 'noise', 'park', 'parking', 'pharmacy', 'pier', 'playground', 'plaza',
      'police', 'pollution', 'population', 'post office', 'prison', 'public', 'restaurant', 'road',
      'shop', 'sidewalk', 'sign', 'skyscraper', 'square', 'stadium', 'station', 'store',
      'street', 'suburb', 'subway', 'supermarket', 'taxi', 'theater', 'tower', 'town',
      'traffic', 'trash', 'village', 'warehouse', 'zone', 'zoo',
    ],
  },
  {
    slug: 'shopping',
    title: 'Покупки',
    description: 'Магазины, товары, цены, оплата',
    iconName: 'ShoppingBag01Icon',
    sortOrder: 16,
    words: [
      'advertise', 'afford', 'aisle', 'auction', 'bargain', 'basket', 'bid', 'brand',
      'buy', 'card', 'cart', 'cash', 'cashier', 'catalog', 'change', 'cheap',
      'checkout', 'color', 'cost', 'counter', 'coupon', 'customer', 'deliver', 'delivery',
      'discount', 'exchange', 'expensive', 'fit', 'goods', 'guarantee', 'invoice', 'label',
      'loyalty', 'market', 'merchant', 'offer', 'order', 'package', 'pay', 'price',
      'product', 'promote', 'quality', 'queue', 'receipt', 'refund', 'retail', 'return',
      'sale', 'save', 'sell', 'shelf', 'shop', 'size', 'spend', 'store',
      'tax', 'tip', 'try', 'value', 'vendor', 'warranty', 'waste', 'wholesale',
      'worth', 'wrap',
    ],
  },
  {
    slug: 'hobbies',
    title: 'Хобби и развлечения',
    description: 'Увлечения, свободное время, развлечения',
    iconName: 'PaintBrushIcon',
    sortOrder: 17,
    words: [
      'art', 'audience', 'bake', 'bet', 'board game', 'calligraphy', 'camera', 'camp',
      'chess', 'climb', 'collect', 'competition', 'concert', 'contest', 'cook', 'craft',
      'creative', 'dance', 'dice', 'draw', 'drum', 'enjoy', 'entertain', 'exhibition',
      'festival', 'film', 'fish', 'fun', 'gamble', 'game', 'garden', 'guitar',
      'hike', 'hobby', 'instrument', 'interest', 'juggle', 'knit', 'leisure', 'magic',
      'movie', 'music', 'origami', 'paint', 'perform', 'photograph', 'piano', 'play',
      'pottery', 'practice', 'prize', 'puzzle', 'read', 'relax', 'reward', 'ride',
      'sculpture', 'sew', 'show', 'sing', 'skate', 'ski', 'skill', 'song',
      'swim', 'talent', 'theater', 'toy', 'travel', 'trick', 'volunteer', 'write',
    ],
  },
  {
    slug: 'time',
    title: 'Время',
    description: 'Время суток, дни недели, месяцы, временные понятия',
    iconName: 'Clock01Icon',
    sortOrder: 18,
    words: [
      'after', 'afternoon', 'ago', 'already', 'always', 'annual', 'april', 'august',
      'autumn', 'before', 'begin', 'century', 'constant', 'continue', 'daily', 'dawn',
      'day', 'deadline', 'decade', 'december', 'delay', 'duration', 'during', 'dusk',
      'early', 'end', 'epoch', 'era', 'evening', 'eventually', 'february', 'finish',
      'frequent', 'friday', 'future', 'gradual', 'hour', 'hurry', 'immediately', 'instant',
      'interval', 'january', 'july', 'june', 'last', 'late', 'march', 'may',
      'meanwhile', 'midnight', 'minute', 'moment', 'monday', 'month', 'monthly', 'morning',
      'never', 'night', 'noon', 'november', 'occasional', 'october', 'often', 'pace',
      'past', 'period', 'permanent', 'postpone', 'present', 'rarely', 'rhythm', 'rush',
      'saturday', 'schedule', 'season', 'second', 'september', 'since', 'sometimes', 'soon',
      'spring', 'start', 'still', 'sudden', 'summer', 'sunday', 'sunrise', 'sunset',
      'temporary', 'thursday', 'time', 'today', 'tomorrow', 'tuesday', 'until', 'usually',
      'wednesday', 'week', 'weekly', 'while', 'winter', 'year', 'yesterday', 'yet',
    ],
  },
  {
    slug: 'money-finance',
    title: 'Деньги и финансы',
    description: 'Деньги, банковские операции, экономика',
    iconName: 'MoneyBag01Icon',
    sortOrder: 19,
    words: [
      'account', 'afford', 'asset', 'balance', 'bank', 'bankrupt', 'bill', 'bond',
      'broker', 'budget', 'cash', 'charity', 'cheap', 'coin', 'cost', 'credit',
      'currency', 'debt', 'deposit', 'dividend', 'dollar', 'donation', 'earn', 'economy',
      'entrepreneur', 'euro', 'exchange', 'expense', 'expensive', 'fee', 'financial', 'fine',
      'fortune', 'fund', 'growth', 'income', 'inflation', 'insurance', 'interest', 'invest',
      'invoice', 'liability', 'loan', 'loss', 'market', 'money', 'mortgage', 'pay',
      'pension', 'poor', 'portfolio', 'pound', 'price', 'profit', 'receipt', 'recession',
      'revenue', 'rich', 'salary', 'save', 'share', 'spend', 'startup', 'stock',
      'subsidy', 'tariff', 'tax', 'tip', 'trade', 'transaction', 'transfer', 'value',
      'wage', 'wealth', 'withdrawal', 'worth',
    ],
  },
  {
    slug: 'appearance',
    title: 'Внешность',
    description: 'Описание внешности, черты лица, фигура',
    iconName: 'UserIcon',
    sortOrder: 20,
    words: [
      'able', 'abnormal', 'above average', 'absent-minded', 'adventurous', 'affectionate', 'agile', 'agreeable',
      'alert', 'amazing', 'ambitious', 'amiable', 'amusing', 'analytical', 'angelic', 'apathetic',
      'appear', 'apprehensive', 'ardent', 'artificial', 'artistic', 'assertive', 'attentive', 'attractive',
      'average', 'awesome', 'awful', 'balanced', 'bald', 'beard', 'beautiful', 'below average',
      'beneficent', 'blonde', 'blue', 'blunt', 'boisterous', 'brave', 'bright', 'brilliant',
      'buff', 'callous', 'candid', 'cantankerous', 'capable', 'careful', 'careless', 'casual',
      'caustic', 'cautious', 'charming', 'cheerful', 'chic', 'childish', 'childlike', 'churlish',
      'circumspect', 'civil', 'clean', 'clever', 'clumsy', 'coherent', 'cold', 'competent',
      'composed', 'conceited', 'condescending', 'confident', 'confused', 'conscientious', 'considerate', 'content',
      'cool', 'cool-headed', 'cooperative', 'cordial', 'courageous', 'cowardly', 'crabby', 'crafty',
      'cranky', 'crass', 'critical', 'cruel', 'curious', 'curly', 'cynical', 'dainty',
      'dark', 'decisive', 'deep', 'deferential', 'deft', 'delicate', 'delightful', 'demonic',
      'demure', 'dependent', 'depressed', 'devoted', 'dextrous', 'diligent', 'direct', 'dirty',
      'disagreeable', 'discerning', 'discreet', 'disruptive', 'distant', 'distraught', 'distrustful', 'dowdy',
      'dramatic', 'dreary', 'dress', 'drowsy', 'drugged', 'drunk', 'dull', 'dutiful',
      'eager', 'earnest', 'easy-going', 'efficient', 'egotistical', 'elegant', 'elfin', 'emotional',
      'energetic', 'enterprising', 'enthusiastic', 'evasive', 'even-tempered', 'exacting', 'excellent', 'excitable',
      'experienced', 'eye', 'fabulous', 'face', 'fastidious', 'fat', 'ferocious', 'fervent',
      'fiery', 'figure', 'fit', 'flabby', 'flaky', 'flashy', 'frank', 'freckle',
      'friendly', 'funny', 'fussy', 'generous', 'gentle', 'gloomy', 'glutinous', 'good',
      'grave', 'great', 'groggy', 'grouchy', 'guarded', 'hair', 'handsome', 'hateful',
      'hearty', 'height', 'helpful', 'hesitant', 'hot-headed', 'hypercritical', 'hysterical', 'idiotic',
      'idle', 'illogical', 'imaginative', 'immature', 'immodest', 'impatient', 'imperturbable', 'impetuous',
      'impractical', 'impressionable', 'impressive', 'impulsive', 'inactive', 'incisive', 'incompetent', 'inconsiderate',
      'inconsistent', 'indefatigable', 'independent', 'indiscreet', 'indolent', 'industrious', 'inexperienced', 'insensitive',
      'inspiring', 'intelligent', 'interesting', 'intolerant', 'inventive', 'irascible', 'irritable', 'irritating',
      'jocular', 'jovial', 'joyous', 'judgmental', 'keen', 'kind', 'lame', 'lazy',
      'lean', 'leery', 'lethargic', 'level-headed', 'listless', 'lithe', 'lively', 'local',
      'logical', 'long-winded', 'look', 'lovable', 'love-lorn', 'lovely', 'maternal', 'mature',
      'mean', 'meddlesome', 'mercurial', 'methodical', 'meticulous', 'mild', 'miserable', 'modest',
      'moronic', 'morose', 'motivated', 'mouth', 'musical', 'mustache', 'naive', 'nasty',
      'natural', 'naughty', 'neat', 'negative', 'nervous', 'noisy', 'normal', 'nose',
      'nosy', 'numb', 'obliging', 'obnoxious', 'old', 'old-fashioned', 'one-sided', 'orderly',
      'ostentatious', 'outgoing', 'outspoken', 'pale', 'passionate', 'passive', 'paternal', 'paternalistic',
      'patient', 'peaceful', 'peevish', 'pensive', 'persevering', 'persnickety', 'petulant', 'picky',
      'plain', 'plain-speaking', 'playful', 'pleasant', 'plucky', 'polite', 'popular', 'positive',
      'powerful', 'practical', 'prejudiced', 'pretty', 'proficient', 'proud', 'provocative', 'prudent',
      'punctual', 'quarrelsome', 'querulous', 'quick', 'quick-tempered', 'quiet', 'realistic', 'reassuring',
      'reclusive', 'recognize', 'reliable', 'reluctant', 'resemble', 'resentful', 'reserved', 'resigned',
      'resourceful', 'respected', 'respectful', 'responsible', 'restless', 'revered', 'ridiculous', 'sad',
      'sassy', 'saucy', 'scar', 'scruffy', 'sedate', 'self-assured', 'selfish', 'sensible',
      'sensitive', 'sentimental', 'serene', 'serious', 'sharp', 'short', 'short-tempered', 'shrewd',
      'shy', 'silly', 'sincere', 'skin', 'sleepy', 'slight', 'slim', 'sloppy',
      'slothful', 'slovenly', 'slow', 'smart', 'snazzy', 'sneering', 'snobby', 'sober',
      'somber', 'sophisticated', 'soulful', 'soulless', 'sour', 'spirited', 'spiteful', 'stable',
      'staid', 'steady', 'stern', 'stoic', 'straight', 'striking', 'strong', 'stupid',
      'sturdy', 'subtle', 'sulky', 'sullen', 'supercilious', 'superficial', 'surly', 'suspicious',
      'sweet', 'tactful', 'tactless', 'talented', 'tall', 'tan', 'testy', 'thin',
      'thinking', 'thoughtful', 'thoughtless', 'timid', 'tired', 'tolerant', 'touchy', 'tranquil',
      'ugly', 'unaffected', 'unbalanced', 'uncertain', 'uncooperative', 'undependable', 'unemotional', 'unfriendly',
      'unguarded', 'unhelpful', 'unimaginative', 'unmotivated', 'unpleasant', 'unpopular', 'unreliable', 'unsophisticated',
      'unstable', 'unsure', 'unthinking', 'unwilling', 'venal', 'versatile', 'vigilant', 'volcanic',
      'vulnerable', 'warm', 'warmhearted', 'wary', 'watchful', 'weak', 'wear', 'weight',
      'well-behaved', 'well-developed', 'well-intentioned', 'well-respected', 'well-rounded', 'willing', 'wonderful', 'wrinkle',
      'young', 'zealous',
    ],
  },
  {
    slug: 'art-culture',
    title: 'Искусство и культура',
    description: 'Живопись, музыка, литература, театр, кино',
    iconName: 'PaintBoardIcon',
    sortOrder: 21,
    words: [
      'abstract', 'actor', 'actress', 'art', 'artist', 'audience', 'author', 'ballet',
      'band', 'biography', 'brush', 'canvas', 'ceremony', 'choir', 'classic', 'comedy',
      'compose', 'concert', 'creative', 'critic', 'culture', 'dance', 'director', 'documentary',
      'drama', 'draw', 'drawing', 'epic', 'exhibition', 'fable', 'fairy tale', 'fantasy',
      'festival', 'fiction', 'film', 'folklore', 'gallery', 'genre', 'harmony', 'heritage',
      'horror', 'illustration', 'inspire', 'instrument', 'landscape', 'legend', 'literature', 'lyrics',
      'masterpiece', 'melody', 'memoir', 'modern', 'movie', 'museum', 'music', 'musician',
      'mystery', 'myth', 'novel', 'opera', 'orchestra', 'paint', 'painting', 'performance',
      'photograph', 'play', 'poem', 'poet', 'portrait', 'premiere', 'rehearse', 'review',
      'rhythm', 'romance', 'scene', 'sculpture', 'sing', 'sketch', 'song', 'stage',
      'style', 'theater', 'tradition', 'tragedy', 'writer',
    ],
  },
  {
    slug: 'science',
    title: 'Наука',
    description: 'Научные дисциплины, исследования, открытия',
    iconName: 'Flask01Icon',
    sortOrder: 22,
    words: [
      'acceleration', 'analyze', 'anthropology', 'astronomy', 'atom', 'bacteria', 'biology', 'calculate',
      'cell', 'chemical', 'chemistry', 'chromosome', 'conclusion', 'constant', 'data', 'discover',
      'discovery', 'ecosystem', 'electricity', 'element', 'energy', 'enzyme', 'equation', 'evidence',
      'evolution', 'experiment', 'fact', 'force', 'formula', 'fossil', 'frequency', 'friction',
      'galaxy', 'gene', 'geology', 'gravity', 'hypothesis', 'laboratory', 'magnet', 'material',
      'mathematics', 'measure', 'method', 'microscope', 'mineral', 'molecule', 'nuclear', 'observe',
      'orbit', 'organism', 'photosynthesis', 'physics', 'planet', 'protein', 'prove', 'psychology',
      'quantum', 'radiation', 'reaction', 'research', 'result', 'satellite', 'science', 'scientist',
      'sociology', 'species', 'spectrum', 'substance', 'telescope', 'temperature', 'theory', 'universe',
      'variable', 'velocity', 'virus', 'wavelength',
    ],
  },
  {
    slug: 'law-politics',
    title: 'Закон и политика',
    description: 'Право, законы, государство, политическая жизнь',
    iconName: 'JusticeScale01Icon',
    sortOrder: 23,
    words: [
      'ambassador', 'amendment', 'appeal', 'arrest', 'assault', 'authority', 'bail', 'ban',
      'bribe', 'campaign', 'candidate', 'citizen', 'coalition', 'comply', 'constitution', 'contract',
      'copyright', 'corruption', 'court', 'crime', 'criminal', 'debate', 'decree', 'democracy',
      'diplomacy', 'election', 'enforce', 'evidence', 'fine', 'fraud', 'freedom', 'government',
      'guilty', 'illegal', 'innocent', 'investigate', 'judge', 'jury', 'justice', 'kidnap',
      'law', 'lawsuit', 'lawyer', 'legal', 'legislation', 'majority', 'minister', 'minority',
      'murder', 'nation', 'opposition', 'parliament', 'parole', 'party', 'patent', 'permit',
      'policy', 'power', 'president', 'prison', 'protest', 'reform', 'regulation', 'republic',
      'revolution', 'right', 'robbery', 'rule', 'sanction', 'sentence', 'smuggle', 'state',
      'suspect', 'theft', 'treaty', 'trial', 'verdict', 'veto', 'victim', 'violate',
      'vote', 'witness',
    ],
  },
  {
    slug: 'communication',
    title: 'Общение и коммуникация',
    description: 'Речь, переписка, медиа, социальные сети',
    iconName: 'MessageChat01Icon',
    sortOrder: 24,
    words: [
      'accent', 'accept', 'advise', 'agree', 'announce', 'answer', 'apologize', 'argue',
      'article', 'ask', 'blog', 'broadcast', 'call', 'channel', 'clarify', 'column',
      'comment', 'communicate', 'complain', 'confirm', 'congratulate', 'conversation', 'convince', 'declare',
      'deny', 'describe', 'dialogue', 'disagree', 'discuss', 'editor', 'email', 'emphasize',
      'explain', 'express', 'follower', 'gesture', 'greet', 'headline', 'interpret', 'interrupt',
      'interview', 'introduce', 'invite', 'journalist', 'language', 'letter', 'magazine', 'media',
      'mention', 'message', 'misunderstand', 'mumble', 'negotiate', 'news', 'newspaper', 'nod',
      'persuade', 'phrase', 'podcast', 'press', 'promise', 'pronounce', 'publish', 'quote',
      'recommend', 'refuse', 'reply', 'report', 'say', 'sentence', 'share', 'shout',
      'signal', 'social', 'speak', 'speech', 'state', 'stutter', 'subscriber', 'suggest',
      'summarize', 'talk', 'tell', 'tone', 'translate', 'viral', 'voice', 'warn',
      'whisper', 'word', 'yell',
    ],
  },
  {
    slug: 'cooking',
    title: 'Кухня и готовка',
    description: 'Приготовление пищи, кухонная утварь, способы готовки',
    iconName: 'CookingPotIcon',
    sortOrder: 25,
    words: [
      'apron', 'bake', 'batter', 'blanch', 'blender', 'boil', 'bowl', 'broth',
      'canned', 'caramelize', 'chef', 'chop', 'colander', 'cook', 'cool', 'cup',
      'cutting board', 'delicious', 'dish', 'dough', 'drain', 'flavor', 'fork', 'freeze',
      'fresh', 'frozen', 'fry', 'garnish', 'glass', 'glaze', 'grater', 'grill',
      'heat', 'homemade', 'ingredient', 'kettle', 'kitchen', 'knead', 'knife', 'ladle',
      'leftovers', 'marinade', 'marinate', 'meal', 'melt', 'microwave', 'mix', 'napkin',
      'organic', 'oven', 'pan', 'peel', 'plate', 'portion', 'pot', 'pour',
      'raw', 'recipe', 'ripe', 'roast', 'rolling pin', 'saucepan', 'sauté', 'season',
      'serve', 'simmer', 'slice', 'smell', 'spatula', 'spoon', 'sprinkle', 'steam',
      'stir', 'stove', 'strain', 'stuff', 'taste', 'toaster', 'tray', 'whisk',
    ],
  },
];
