import type { IconSvgElement } from '@hugeicons/react';
import {
  Bug02Icon,
  Coffee01Icon,
  Home01Icon,
  Shirt01Icon,
  HeartCheckIcon,
  UserGroupIcon,
  Briefcase01Icon,
  AirplaneTakeOff01Icon,
  WorkoutRunIcon,
  Sun03Icon,
  Car01Icon,
  MortarboardIcon,
  SmileIcon,
  LaptopIcon,
  Building01Icon,
  ShoppingBag01Icon,
  PaintBrush01Icon,
  Clock01Icon,
  MoneyBag01Icon,
  UserIcon,
  PaintBoardIcon,
  Chemistry01Icon,
  JusticeScale01Icon,
  Message01Icon,
  Restaurant01Icon,
  BookOpen02Icon,
  Book02Icon,
  UniversityIcon,
  ShuffleIcon,
} from '@hugeicons/core-free-icons';

// Маппинг имён иконок из базы данных на компоненты Hugeicons
export const ICON_MAP: Record<string, IconSvgElement> = {
  Bug02Icon,
  CoffeeIcon: Coffee01Icon,
  Home01Icon,
  Shirt01Icon,
  HeartCheckIcon,
  UserGroupIcon,
  Briefcase01Icon,
  AirplaneTakeOff01Icon,
  WorkoutRunIcon,
  Sun03Icon,
  Car01Icon,
  MortarboardIcon,
  SmileFaceIcon: SmileIcon,
  Laptop01Icon: LaptopIcon,
  Building01Icon,
  ShoppingBag01Icon,
  PaintBrushIcon: PaintBrush01Icon,
  Clock01Icon,
  MoneyBag01Icon,
  UserIcon,
  PaintBoardIcon,
  Flask01Icon: Chemistry01Icon,
  JusticeScale01Icon,
  MessageChat01Icon: Message01Icon,
  CookingPotIcon: Restaurant01Icon,
  BookOpen02Icon,
  Book02Icon,
  UniversityIcon,
  Shuffle01Icon: ShuffleIcon,
};

export const DEFAULT_ICON = BookOpen02Icon;
